INFO     16:13:22 [logs.log:31] : 文件file=WindowsPath('D:/Python_project/ui_1129/excel_data/test_excel.xlsx'),包含了1个sheet页
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：('步骤ID', '步骤名称', '关键字', '参数', None)
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：(-1, '用例名称', 'name', '更改头像，更改成功', None)
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：(1, '使用fixture启动浏览器', 'driver_fixture', 'user_driver', None)
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：(2, '访问个人信息页', 'get_page', 'http://shop-xo.hctestedu.com/index.php?s=/index/personal/index.html', None)
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：(3, '点击修改按钮', 'click', "//*[text()='修改' and @href='javascript:;']", None)
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：(4, '执行JS脚本', 'js_code', '//*[@id="user-avatar-popup"]/div/div[2]/form/div[2]/div/input', 'arguments[0].style="position: static;"')
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：(5, '上传图片', 'upload', '//*[@id="user-avatar-popup"]/div/div[2]/form/div[2]/div/input', 'D:\\1.png')
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：(6, '点击确认上传', 'click', "//*[text()='确认上传']", None)
DEBUG    16:13:22 [logs.log:38] : 正在处理下一行：(7, '断言', 'assert_equal_text', '//*[@class="prompt-msg"]', '上传成功')
INFO     16:13:22 [logs.log:45] : Sheet'个人信息-',包含了1条用例
DEBUG    16:13:22 [logs.log:47] : 生成测试用例suite_dict={'个人信息-': {'更改头像，更改成功': [[1, '使用fixture启动浏览器', 'driver_fixture', 'user_driver'], [2, '访问个人信息页', 'get_page', 'http://shop-xo.hctestedu.com/index.php?s=/index/personal/index.html'], [3, '点击修改按钮', 'click', "//*[text()='修改' and @href='javascript:;']"], [4, '执行JS脚本', 'js_code', '//*[@id="user-avatar-popup"]/div/div[2]/form/div[2]/div/input', 'arguments[0].style="position: static;"'], [5, '上传图片', 'upload', '//*[@id="user-avatar-popup"]/div/div[2]/form/div[2]/div/input', 'D:\\1.png'], [6, '点击确认上传', 'click', "//*[text()='确认上传']"], [7, '断言', 'assert_equal_text', '//*[@class="prompt-msg"]', '上传成功']]}}
INFO     16:13:22 [logs.log:114] : 生成了测试用例个人信息-
INFO     16:13:22 [logs.log:19] : 所有excel文件测试用例生成完成
WARNING  16:13:22 [logs.log:70] : ----------------个人信息-.更改头像，更改成功测试开始----------------
INFO     16:13:22 [logs.log:78] : 执行关键字：key='driver_fixture',args=['user_driver']
INFO     16:13:22 [logs.log:109] : 正在使用Chrome浏览器
DEBUG    16:13:22 [selenium.webdriver.common.service:198] : Started executable: `chromedriver` in a child process with pid: 13416
DEBUG    16:13:23 [selenium.webdriver.remote.remote_connection:308] : POST http://localhost:8775/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}}
DEBUG    16:13:23 [urllib3.connectionpool:228] : Starting new HTTP connection (1): localhost:8775
DEBUG    16:13:24 [urllib3.connectionpool:456] : http://localhost:8775 "POST /session HTTP/1.1" 200 790
DEBUG    16:13:24 [selenium.webdriver.remote.remote_connection:330] : Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"107.0.5304.122","chrome":{"chromedriverVersion":"107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942})","userDataDir":"C:\\Users\\sixyco\\AppData\\Local\\Temp\\scoped_dir13416_740057356"},"goog:chromeOptions":{"debuggerAddress":"localhost:8778"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:virtualAuthenticators":true},"sessionId":"1a429e4e919be406706472417bc09b55"}} | headers=HTTPHeaderDict({'Content-Length': '790', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    16:13:24 [selenium.webdriver.remote.remote_connection:358] : Finished Request
DEBUG    16:13:24 [selenium.webdriver.remote.remote_connection:308] : POST http://localhost:8775/session/1a429e4e919be406706472417bc09b55/window/maximize {}
DEBUG    16:13:24 [urllib3.connectionpool:456] : http://localhost:8775 "POST /session/1a429e4e919be406706472417bc09b55/window/maximize HTTP/1.1" 200 51
DEBUG    16:13:24 [selenium.webdriver.remote.remote_connection:330] : Remote response: status=200 | data={"value":{"height":840,"width":1552,"x":-8,"y":-8}} | headers=HTTPHeaderDict({'Content-Length': '51', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    16:13:24 [selenium.webdriver.remote.remote_connection:358] : Finished Request
INFO     16:13:24 [logs.log:139] : 正在以最大化窗口运行浏览器
DEBUG    16:13:24 [selenium.webdriver.remote.remote_connection:308] : POST http://localhost:8775/session/1a429e4e919be406706472417bc09b55/url {"url": "http://101.34.221.219:8010/"}
DEBUG    16:13:32 [urllib3.connectionpool:456] : http://localhost:8775 "POST /session/1a429e4e919be406706472417bc09b55/url HTTP/1.1" 200 14
DEBUG    16:13:32 [selenium.webdriver.remote.remote_connection:330] : Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    16:13:32 [selenium.webdriver.remote.remote_connection:358] : Finished Request
INFO     16:13:32 [logs.log:88] : 加载cookies[{'name': 'PHPSESSID', 'value': '76ies0j9pcdoenl7tbjjj5ha73', 'path': '/', 'domain': 'shop-xo.hctestedu.com', 'secure': False, 'httpOnly': True, 'sameSite': 'None'}, {'name': 'PHPSESSID', 'value': 'ti8lep4826tltrksf7cct4bu7v', 'path': '/', 'domain': '.shop-xo.hctestedu.com', 'secure': False, 'httpOnly': True, 'sameSite': 'None'}, {'name': 'SECKEY_ABVK', 'value': 'VmP5xGI6PgeVfQSb8X/qOiSq6gpZGEfFzoo2/oYfLC8%3D', 'path': '/', 'domain': '.shop-xo.hctestedu.com', 'secure': False, 'httpOnly': False, 'expiry': 1672378876, 'sameSite': 'None'}, {'name': 'BMAP_SECKEY', 'value': '0Fx9c6ztE1uH5feeDjKWJKx-K9FLQF7DDScEwMfAt1pnlRN7JhvKmFO4i5uMtoOFUVkF8LJ8vAoFmiyF7knnpBy4anaXup75YYDvl9iFFTtNo30gps_gsmwEv1EKvZtNrpnnDZQL2EjUFshhyCS4l6njb52MZM0dRueaS4NbV0ZDynQxDKM8AQmTA5kQBj4j4GXiDv9vzyiaYn61UQlsxw', 'path': '/', 'domain': '.shop-xo.hctestedu.com', 'secure': False, 'httpOnly': False, 'expiry': 1672378877, 'sameSite': 'None'}, {'name': 'SECKEY_ABVK', 'value': 'VmP5xGI6PgeVfQSb8X/qOrqV62Tux5+VDfMNVReL7ag%3D', 'path': '/', 'domain': 'shop-xo.hctestedu.com', 'secure': False, 'httpOnly': False, 'expiry': 1672378908, 'sameSite': 'None'}, {'name': 'BMAP_SECKEY', 'value': '0Fx9c6ztE1uH5feeDjKWJCTtGBgiZz7cMUbIwDrRlWrZu-kHwgKaxJ2HhL4qTk28snUJ9-wbzNgMzrJJthV36iUyAQYNmdvbrOTafXmSyK4M0RHOGJGLOpgtIeD52N8qAEmIiAgpQQM5KybUyDALFG-i-DHk6_LMgamq8Nf_X9tC0Vkpjeae_Xz01CypU3kL1Cac5oOA5fQQbX0VtWQwnw', 'path': '/', 'domain': 'shop-xo.hctestedu.com', 'secure': False, 'httpOnly': False, 'expiry': 1672378908, 'sameSite': 'None'}]
DEBUG    16:13:32 [selenium.webdriver.remote.remote_connection:308] : POST http://localhost:8775/session/1a429e4e919be406706472417bc09b55/cookie {"cookie": {"name": "PHPSESSID", "value": "76ies0j9pcdoenl7tbjjj5ha73", "path": "/", "domain": "shop-xo.hctestedu.com", "secure": false, "httpOnly": true, "sameSite": "None"}}
DEBUG    16:13:32 [urllib3.connectionpool:456] : http://localhost:8775 "POST /session/1a429e4e919be406706472417bc09b55/cookie HTTP/1.1" 400 908
DEBUG    16:13:32 [selenium.webdriver.remote.remote_connection:330] : Remote response: status=400 | data={"value":{"error":"invalid cookie domain","message":"invalid cookie domain: Cookie 'domain' mismatch\n  (Session info: chrome=107.0.5304.122)","stacktrace":"Backtrace:\n\tOrdinal0 [0x00A8ACD3+2075859]\n\tOrdinal0 [0x00A1EE61+1633889]\n\tOrdinal0 [0x0091B7BD+571325]\n\tOrdinal0 [0x0098A45B+1025115]\n\tOrdinal0 [0x0096731C+881436]\n\tOrdinal0 [0x0097B56A+963946]\n\tOrdinal0 [0x00967136+880950]\n\tOrdinal0 [0x0093FEFD+720637]\n\tOrdinal0 [0x00940F3F+724799]\n\tGetHandleVerifier [0x00D3EED2+2769538]\n\tGetHandleVerifier [0x00D30D95+2711877]\n\tGetHandleVerifier [0x00B1A03A+521194]\n\tGetHandleVerifier [0x00B18DA0+516432]\n\tOrdinal0 [0x00A2682C+1665068]\n\tOrdinal0 [0x00A2B128+1683752]\n\tOrdinal0 [0x00A2B215+1683989]\n\tOrdinal0 [0x00A36484+1729668]\n\tBaseThreadInitThunk [0x7599FEF9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77B27BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77B27B8E+238]\n"}} | headers=HTTPHeaderDict({'Content-Length': '908', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    16:13:32 [selenium.webdriver.remote.remote_connection:358] : Finished Request
ERROR    16:13:32 [logs.log:90] : 关键字调用出错
Traceback (most recent call last):
  File "D:\Python_project\ui_1129\core\excel_kdt.py", line 82, in test_
    f(*args)
  File "D:\Python_project\ui_1129\core\kdt.py", line 143, in key_driver_fixture
    driver = self.request.getfixturevalue(fixture_name)  # 根据字符串来启动夹具
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 568, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 590, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 676, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 1074, in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 1128, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 900, in call_fixture_func
    fixture_result = next(generator)
                     ^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\conftest.py", line 142, in user_driver
    set_cookies(driver)  # 加载登录状态
    ^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\conftest.py", line 90, in set_cookies
    driver.add_cookie(cookie)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 749, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=107.0.5304.122)
Stacktrace:
Backtrace:
	Ordinal0 [0x00A8ACD3+2075859]
	Ordinal0 [0x00A1EE61+1633889]
	Ordinal0 [0x0091B7BD+571325]
	Ordinal0 [0x0098A45B+1025115]
	Ordinal0 [0x0096731C+881436]
	Ordinal0 [0x0097B56A+963946]
	Ordinal0 [0x00967136+880950]
	Ordinal0 [0x0093FEFD+720637]
	Ordinal0 [0x00940F3F+724799]
	GetHandleVerifier [0x00D3EED2+2769538]
	GetHandleVerifier [0x00D30D95+2711877]
	GetHandleVerifier [0x00B1A03A+521194]
	GetHandleVerifier [0x00B18DA0+516432]
	Ordinal0 [0x00A2682C+1665068]
	Ordinal0 [0x00A2B128+1683752]
	Ordinal0 [0x00A2B215+1683989]
	Ordinal0 [0x00A36484+1729668]
	BaseThreadInitThunk [0x7599FEF9+25]
	RtlGetAppContainerNamedObjectPath [0x77B27BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77B27B8E+238]

ERROR    16:13:32 [logs.log:110] : 个人信息-.更改头像，更改成功测试失败
Traceback (most recent call last):
  File "D:\Python_project\ui_1129\core\excel_kdt.py", line 82, in test_
    f(*args)
  File "D:\Python_project\ui_1129\core\kdt.py", line 143, in key_driver_fixture
    driver = self.request.getfixturevalue(fixture_name)  # 根据字符串来启动夹具
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 568, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 590, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 676, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 1074, in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 1128, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 900, in call_fixture_func
    fixture_result = next(generator)
                     ^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\conftest.py", line 142, in user_driver
    set_cookies(driver)  # 加载登录状态
    ^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\conftest.py", line 90, in set_cookies
    driver.add_cookie(cookie)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 749, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=107.0.5304.122)
Stacktrace:
Backtrace:
	Ordinal0 [0x00A8ACD3+2075859]
	Ordinal0 [0x00A1EE61+1633889]
	Ordinal0 [0x0091B7BD+571325]
	Ordinal0 [0x0098A45B+1025115]
	Ordinal0 [0x0096731C+881436]
	Ordinal0 [0x0097B56A+963946]
	Ordinal0 [0x00967136+880950]
	Ordinal0 [0x0093FEFD+720637]
	Ordinal0 [0x00940F3F+724799]
	GetHandleVerifier [0x00D3EED2+2769538]
	GetHandleVerifier [0x00D30D95+2711877]
	GetHandleVerifier [0x00B1A03A+521194]
	GetHandleVerifier [0x00B18DA0+516432]
	Ordinal0 [0x00A2682C+1665068]
	Ordinal0 [0x00A2B128+1683752]
	Ordinal0 [0x00A2B215+1683989]
	Ordinal0 [0x00A36484+1729668]
	BaseThreadInitThunk [0x7599FEF9+25]
	RtlGetAppContainerNamedObjectPath [0x77B27BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77B27B8E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_project\ui_1129\core\excel_kdt.py", line 93, in test_
    kw.driver.get_screenshot_as_png(),
    ^^^^^^^^^
AttributeError: 'KeyWord' object has no attribute 'driver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_project\ui_1129\core\excel_kdt.py", line 101, in test_
    kw.driver.get_screenshot_as_png(),
    ^^^^^^^^^
AttributeError: 'KeyWord' object has no attribute 'driver'
WARNING  16:13:32 [logs.log:70] : ----------------个人信息-.更改头像，更改成功测试开始----------------
INFO     16:13:32 [logs.log:78] : 执行关键字：key='driver_fixture',args=['user_driver']
INFO     16:13:32 [logs.log:109] : 正在使用Chrome浏览器
DEBUG    16:13:32 [selenium.webdriver.common.service:198] : Started executable: `chromedriver` in a child process with pid: 6908
DEBUG    16:13:32 [selenium.webdriver.remote.remote_connection:308] : POST http://localhost:8804/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}}
DEBUG    16:13:32 [urllib3.connectionpool:228] : Starting new HTTP connection (1): localhost:8804
DEBUG    16:13:34 [urllib3.connectionpool:456] : http://localhost:8804 "POST /session HTTP/1.1" 200 790
DEBUG    16:13:34 [selenium.webdriver.remote.remote_connection:330] : Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"107.0.5304.122","chrome":{"chromedriverVersion":"107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942})","userDataDir":"C:\\Users\\sixyco\\AppData\\Local\\Temp\\scoped_dir6908_1020357511"},"goog:chromeOptions":{"debuggerAddress":"localhost:8807"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:virtualAuthenticators":true},"sessionId":"726d171ea34022cab7923fec61788bd8"}} | headers=HTTPHeaderDict({'Content-Length': '790', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    16:13:34 [selenium.webdriver.remote.remote_connection:358] : Finished Request
DEBUG    16:13:34 [selenium.webdriver.remote.remote_connection:308] : POST http://localhost:8804/session/726d171ea34022cab7923fec61788bd8/window/maximize {}
DEBUG    16:13:34 [urllib3.connectionpool:456] : http://localhost:8804 "POST /session/726d171ea34022cab7923fec61788bd8/window/maximize HTTP/1.1" 200 51
DEBUG    16:13:34 [selenium.webdriver.remote.remote_connection:330] : Remote response: status=200 | data={"value":{"height":840,"width":1552,"x":-8,"y":-8}} | headers=HTTPHeaderDict({'Content-Length': '51', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    16:13:34 [selenium.webdriver.remote.remote_connection:358] : Finished Request
INFO     16:13:34 [logs.log:139] : 正在以最大化窗口运行浏览器
DEBUG    16:13:34 [selenium.webdriver.remote.remote_connection:308] : POST http://localhost:8804/session/726d171ea34022cab7923fec61788bd8/url {"url": "http://101.34.221.219:8010/"}
DEBUG    16:13:41 [urllib3.connectionpool:456] : http://localhost:8804 "POST /session/726d171ea34022cab7923fec61788bd8/url HTTP/1.1" 200 14
DEBUG    16:13:41 [selenium.webdriver.remote.remote_connection:330] : Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    16:13:41 [selenium.webdriver.remote.remote_connection:358] : Finished Request
INFO     16:13:41 [logs.log:88] : 加载cookies[{'name': 'PHPSESSID', 'value': '76ies0j9pcdoenl7tbjjj5ha73', 'path': '/', 'domain': 'shop-xo.hctestedu.com', 'secure': False, 'httpOnly': True, 'sameSite': 'None'}, {'name': 'PHPSESSID', 'value': 'ti8lep4826tltrksf7cct4bu7v', 'path': '/', 'domain': '.shop-xo.hctestedu.com', 'secure': False, 'httpOnly': True, 'sameSite': 'None'}, {'name': 'SECKEY_ABVK', 'value': 'VmP5xGI6PgeVfQSb8X/qOiSq6gpZGEfFzoo2/oYfLC8%3D', 'path': '/', 'domain': '.shop-xo.hctestedu.com', 'secure': False, 'httpOnly': False, 'expiry': 1672378876, 'sameSite': 'None'}, {'name': 'BMAP_SECKEY', 'value': '0Fx9c6ztE1uH5feeDjKWJKx-K9FLQF7DDScEwMfAt1pnlRN7JhvKmFO4i5uMtoOFUVkF8LJ8vAoFmiyF7knnpBy4anaXup75YYDvl9iFFTtNo30gps_gsmwEv1EKvZtNrpnnDZQL2EjUFshhyCS4l6njb52MZM0dRueaS4NbV0ZDynQxDKM8AQmTA5kQBj4j4GXiDv9vzyiaYn61UQlsxw', 'path': '/', 'domain': '.shop-xo.hctestedu.com', 'secure': False, 'httpOnly': False, 'expiry': 1672378877, 'sameSite': 'None'}, {'name': 'SECKEY_ABVK', 'value': 'VmP5xGI6PgeVfQSb8X/qOrqV62Tux5+VDfMNVReL7ag%3D', 'path': '/', 'domain': 'shop-xo.hctestedu.com', 'secure': False, 'httpOnly': False, 'expiry': 1672378908, 'sameSite': 'None'}, {'name': 'BMAP_SECKEY', 'value': '0Fx9c6ztE1uH5feeDjKWJCTtGBgiZz7cMUbIwDrRlWrZu-kHwgKaxJ2HhL4qTk28snUJ9-wbzNgMzrJJthV36iUyAQYNmdvbrOTafXmSyK4M0RHOGJGLOpgtIeD52N8qAEmIiAgpQQM5KybUyDALFG-i-DHk6_LMgamq8Nf_X9tC0Vkpjeae_Xz01CypU3kL1Cac5oOA5fQQbX0VtWQwnw', 'path': '/', 'domain': 'shop-xo.hctestedu.com', 'secure': False, 'httpOnly': False, 'expiry': 1672378908, 'sameSite': 'None'}]
DEBUG    16:13:41 [selenium.webdriver.remote.remote_connection:308] : POST http://localhost:8804/session/726d171ea34022cab7923fec61788bd8/cookie {"cookie": {"name": "PHPSESSID", "value": "76ies0j9pcdoenl7tbjjj5ha73", "path": "/", "domain": "shop-xo.hctestedu.com", "secure": false, "httpOnly": true, "sameSite": "None"}}
DEBUG    16:13:41 [urllib3.connectionpool:456] : http://localhost:8804 "POST /session/726d171ea34022cab7923fec61788bd8/cookie HTTP/1.1" 400 908
DEBUG    16:13:41 [selenium.webdriver.remote.remote_connection:330] : Remote response: status=400 | data={"value":{"error":"invalid cookie domain","message":"invalid cookie domain: Cookie 'domain' mismatch\n  (Session info: chrome=107.0.5304.122)","stacktrace":"Backtrace:\n\tOrdinal0 [0x00A8ACD3+2075859]\n\tOrdinal0 [0x00A1EE61+1633889]\n\tOrdinal0 [0x0091B7BD+571325]\n\tOrdinal0 [0x0098A45B+1025115]\n\tOrdinal0 [0x0096731C+881436]\n\tOrdinal0 [0x0097B56A+963946]\n\tOrdinal0 [0x00967136+880950]\n\tOrdinal0 [0x0093FEFD+720637]\n\tOrdinal0 [0x00940F3F+724799]\n\tGetHandleVerifier [0x00D3EED2+2769538]\n\tGetHandleVerifier [0x00D30D95+2711877]\n\tGetHandleVerifier [0x00B1A03A+521194]\n\tGetHandleVerifier [0x00B18DA0+516432]\n\tOrdinal0 [0x00A2682C+1665068]\n\tOrdinal0 [0x00A2B128+1683752]\n\tOrdinal0 [0x00A2B215+1683989]\n\tOrdinal0 [0x00A36484+1729668]\n\tBaseThreadInitThunk [0x7599FEF9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77B27BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77B27B8E+238]\n"}} | headers=HTTPHeaderDict({'Content-Length': '908', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    16:13:41 [selenium.webdriver.remote.remote_connection:358] : Finished Request
ERROR    16:13:41 [logs.log:90] : 关键字调用出错
Traceback (most recent call last):
  File "D:\Python_project\ui_1129\core\excel_kdt.py", line 82, in test_
    f(*args)
  File "D:\Python_project\ui_1129\core\kdt.py", line 143, in key_driver_fixture
    driver = self.request.getfixturevalue(fixture_name)  # 根据字符串来启动夹具
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 568, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 590, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 676, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 1074, in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 1128, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 900, in call_fixture_func
    fixture_result = next(generator)
                     ^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\conftest.py", line 142, in user_driver
    set_cookies(driver)  # 加载登录状态
    ^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\conftest.py", line 90, in set_cookies
    driver.add_cookie(cookie)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 749, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=107.0.5304.122)
Stacktrace:
Backtrace:
	Ordinal0 [0x00A8ACD3+2075859]
	Ordinal0 [0x00A1EE61+1633889]
	Ordinal0 [0x0091B7BD+571325]
	Ordinal0 [0x0098A45B+1025115]
	Ordinal0 [0x0096731C+881436]
	Ordinal0 [0x0097B56A+963946]
	Ordinal0 [0x00967136+880950]
	Ordinal0 [0x0093FEFD+720637]
	Ordinal0 [0x00940F3F+724799]
	GetHandleVerifier [0x00D3EED2+2769538]
	GetHandleVerifier [0x00D30D95+2711877]
	GetHandleVerifier [0x00B1A03A+521194]
	GetHandleVerifier [0x00B18DA0+516432]
	Ordinal0 [0x00A2682C+1665068]
	Ordinal0 [0x00A2B128+1683752]
	Ordinal0 [0x00A2B215+1683989]
	Ordinal0 [0x00A36484+1729668]
	BaseThreadInitThunk [0x7599FEF9+25]
	RtlGetAppContainerNamedObjectPath [0x77B27BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77B27B8E+238]

ERROR    16:13:41 [logs.log:110] : 个人信息-.更改头像，更改成功测试失败
Traceback (most recent call last):
  File "D:\Python_project\ui_1129\core\excel_kdt.py", line 82, in test_
    f(*args)
  File "D:\Python_project\ui_1129\core\kdt.py", line 143, in key_driver_fixture
    driver = self.request.getfixturevalue(fixture_name)  # 根据字符串来启动夹具
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 568, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 590, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 676, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 1074, in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 1128, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\_pytest\fixtures.py", line 900, in call_fixture_func
    fixture_result = next(generator)
                     ^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\conftest.py", line 142, in user_driver
    set_cookies(driver)  # 加载登录状态
    ^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ui_1129\conftest.py", line 90, in set_cookies
    driver.add_cookie(cookie)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 749, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "D:\Python_project\ui_1129\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=107.0.5304.122)
Stacktrace:
Backtrace:
	Ordinal0 [0x00A8ACD3+2075859]
	Ordinal0 [0x00A1EE61+1633889]
	Ordinal0 [0x0091B7BD+571325]
	Ordinal0 [0x0098A45B+1025115]
	Ordinal0 [0x0096731C+881436]
	Ordinal0 [0x0097B56A+963946]
	Ordinal0 [0x00967136+880950]
	Ordinal0 [0x0093FEFD+720637]
	Ordinal0 [0x00940F3F+724799]
	GetHandleVerifier [0x00D3EED2+2769538]
	GetHandleVerifier [0x00D30D95+2711877]
	GetHandleVerifier [0x00B1A03A+521194]
	GetHandleVerifier [0x00B18DA0+516432]
	Ordinal0 [0x00A2682C+1665068]
	Ordinal0 [0x00A2B128+1683752]
	Ordinal0 [0x00A2B215+1683989]
	Ordinal0 [0x00A36484+1729668]
	BaseThreadInitThunk [0x7599FEF9+25]
	RtlGetAppContainerNamedObjectPath [0x77B27BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77B27B8E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_project\ui_1129\core\excel_kdt.py", line 93, in test_
    kw.driver.get_screenshot_as_png(),
    ^^^^^^^^^
AttributeError: 'KeyWord' object has no attribute 'driver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_project\ui_1129\core\excel_kdt.py", line 101, in test_
    kw.driver.get_screenshot_as_png(),
    ^^^^^^^^^
AttributeError: 'KeyWord' object has no attribute 'driver'
